---
kind: pipeline
type: docker
name: deploy-sergio.am

steps:
- name: build
  image: pandoc/core:latest
  commands:
    - bash ./build.sh
    - mv _site /var/www/

when:
  branch:
  - main

node:
  location: nexus
