---
kind: pipeline
type: docker
name: deploy-sergio.am

steps:
- name: build
  image: alpine:latest
  commands:
    - apk update && apk add bash jq pandoc
    - bash ./build.sh
    - mv _site /var/www/

when:
  branch:
  - main

node:
  location: nexus
