---
kind: pipeline
type: docker
name: deploy-jekyll-sergio.am

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: bundle-cache
    path: /cache
  settings:
    restore: true
    mount:
    - /drone/.bundle

- name: build
  image: ruby:latest
  environment:
    - BUNDLE_PATH=/drone/.bundle
  commands:
    - bundle install
    - bundle exec jekyll build

- name: rebuild-cache
  image: drillster/drone-volume-cache 
  volumes:
  - name: bundle-cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - /drone/.bundle

when:
  branch:
  - main

node:
  location: marley

volumes:
- name: bundle-cache
  host:
    path: /tmp/ruby-bundle-cache-sergio.am
