---
kind: pipeline
type: docker
name: deploy-jekyll-sergio.am

steps:
- name: build
  image: ruby:latest
  volumes:
  - name: bundle-cache
    path: /cache
  commands:
    - bundle config set --local path /cache/.bundle
    - bundle install
    - bundle exec jekyll build --destination /var/www/_site --incremental

when:
  branch:
  - main

node:
  location: nexus

volumes:
- name: bundle-cache
  host:
    path: /var/lib/drone/temp/ruby-bundle-cache-sergio.am
